development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_production
  pool: 5
  username: root
  password: lolopoP9
  socket: /run/mysqld/mysqld.sock


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_test
  pool: 5
  username: root
  password:
  socket: /run/mysqld/mysqld.sock


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_production
  pool: 5
  username: root
  password: lolopoP9
  socket: /var/run/mysqld/mysqld.sock
